---

- name: Install Bareos repository (CentOS 7 or Virtuozzo 7)
  yum_repository:
    name: "bareos_bareos-{{ bareos_repo_release }}"
    description: "bareos_bareos-{{ bareos_repo_release }}"
    baseurl: "http://download.bareos.org/bareos/release/{{ bareos_repo_release }}/CentOS_7/"
    gpgcheck: yes
    gpgkey: "http://download.bareos.org/bareos/release/{{ bareos_repo_release }}/CentOS_7/repodata/repomd.xml.key"
    enabled: yes
