---

- name: Add apt key (Debian 9)
  apt_key:
    url: "http://download.bareos.org/bareos/release/{{ bareos_repo_release }}/Debian_9.0/Release.key"
    state: present

- name: Install Bareos repository (Debian 9)
  apt_repository:
    repo: "deb http://download.bareos.org/bareos/release/{{ bareos_repo_release }}/Debian_9.0 /"
    state: present
    filename: "bareos"
