---

# Repo installation
- include: centos_6_repo.yml
  when: >
    ansible_distribution == "CentOS" and 
    ansible_distribution_major_version == "6"

- include: centos_7_repo.yml
  when: >
    ansible_distribution == "CentOS" and
    ansible_distribution_major_version == "7"

- include: centos_8_repo.yml
  when: >
    ansible_distribution == "CentOS" and
    ansible_distribution_major_version == "8"

- include: debian_8_repo.yml
  when: >
    ansible_distribution == "Debian" and
    ansible_distribution_major_version == "8"

- include: debian_9_repo.yml
  when: >
    ansible_distribution == "Debian" and
    ansible_distribution_major_version == "9"

- include: debian_10_repo.yml
  when: >
    ansible_distribution == "Debian" and
    ansible_distribution_major_version == "10"

- include: ubuntu_16.04_repo.yml
  when: >
    ansible_distribution == "Ubuntu" and
    ansible_distribution_major_version == "16.04"

- include: ubuntu_18.04_repo.yml
  when: >
    ansible_distribution == "Ubuntu" and
    ansible_distribution_major_version == "18.04"
