---

# Repo installation
- include: centos_6_repo.yml
  when: >
    ansible_distribution == "CentOS" and 
    ansible_distribution_major_version == '6'

- include: centos_7_repo.yml
  when: >
    ansible_distribution == "CentOS" and
    ansible_distribution_major_version == '7'
