---

- name: Install Bareos repository (Ubuntu 18.04)
  apt_repository:
    repo: "http://download.bareos.org/bareos/release/{{ bareos_version }}/xUbuntu_18.04/"
    state: present

- name: Add apt key (Ubuntu 18.04)
  apt_key:
    url: "http://download.bareos.org/bareos/release/{{ bareos_version }}/xUbuntu_18.04/Release.key"
    state: present
